# Generated by Django 5.1.7 on 2026-04-25 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_notification_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, default='Sống tại Hà Nội, Việt Nam', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='passion',
            field=models.CharField(blank=True, default='Đam mê nấu ăn', max_length=200, null=True),
        ),
    ]
