# Generated by Django 5.1.7 on 2026-05-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_systemsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notif_browser',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notif_email',
            field=models.BooleanField(default=False),
        ),
    ]
