# Generated by Django 5.1.7 on 2026-05-07 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_user_notif_browser_user_notif_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataaccesslog',
            name='endpoint',
            field=models.CharField(default='/', max_length=200),
        ),
        migrations.AddField(
            model_name='dataaccesslog',
            name='method',
            field=models.CharField(default='GET', max_length=10),
        ),
        migrations.AddField(
            model_name='dataaccesslog',
            name='response_status',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='thirdparty',
            name='company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='thirdparty',
            name='company_size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='thirdparty',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='thirdparty',
            name='partner_email',
            field=models.EmailField(default='default@example.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thirdparty',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='thirdparty',
            name='tier',
            field=models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium')], default='free', max_length=20),
        ),
    ]
