# Generated by Django 5.1.7 on 2026-04-25 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_location_user_passion'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
