# Generated by Django 5.1.7 on 2026-05-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_post_province'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('setting_id', models.AutoField(primary_key=True, serialize=False)),
                ('app_name', models.CharField(default='Ẩm Thực 3 Miền', max_length=100)),
                ('slogan', models.CharField(default='Nâng tầm văn hóa ẩm thực Việt', max_length=200)),
                ('facebook_page', models.CharField(default='https://facebook.com/cuisine3mien', max_length=200)),
                ('hotline', models.CharField(default='1900 1234', max_length=20)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('admin_email', models.EmailField(default='admin@cuisine.vn', max_length=254)),
            ],
        ),
    ]
